config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :privacies
  resources :permissions
  resources :users
  resources :documents
  resources :folders, :path => 'mytopbox'
  resources :permissions

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  #Login / Sign Up / Session
  root 'sessions#new'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #recycle
  post "documents/:id/recycle" => "documents#recycle", as: :document_recycle
  post "documents/:id/trash" => "documents#move_to_trash", as: :document_move_to_trash
  post "folders/:id/recycle" => "folders#recycle", as: :folder_recycle
  post "folders/:id/trash" => "folders#move_to_trash", as: :folder_move_to_trash
  get "trash" => "folders#show_trash"
  post "trash/recycle" => "folders#recycle_all", as: :recycle_all
  post "trash/destroy_all" => "folders#trash_destroy_all", as: :trash_destroy_all


  get 'denied' => 'permissions#denied'
  get 'makeopen' => 'privacies#open'
  get 'shared' => 'folders#shared'
  get 'notifications' => 'notification#index'
  get 'documents/:id/visibility' => 'privacies#switch_visibility', :as => 'document_visibility'
  get 'documents/:id/download' => 'documents#download', :as => 'document_download'
  post 'documents/:id/compress' => 'documents#compress', :as => 'document_compress'
  post 'documents/:id/decompress' => 'documents#decompress', :as => 'document_decompress'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  match "/auth/:provider/callback" => "sessions#create", as: :auth_callback, via: [:get, :post]


end

app/models/folder.rb
class Folder < ApplicationRecord
  belongs_to :user
  belongs_to :parent, class_name: 'Folder'
  has_many :children, :dependent => :destroy, class_name: 'Folder', :foreign_key => 'parent_id'
  has_many :documents, :dependent => :destroy, class_name: 'Document'
  validates :name, presence: true
	
	def make_trash
  		self.update trash: true
    	self.documents.each do |doc| 
      	doc.make_trash
    	end
    	self.children.each do |child|
      	child.make_trash
    	end
    end

    def make_recycle
    	self.update trash: false
    	self.documents.each do |doc| 
      	doc.make_recycle
    	end
    	self.children.each do |child|
      	child.make_recycle
    	end
    end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  include FoldersHelper, ApplicationHelper
  before_action :require_user, only: [:index, :show, :edit, :update, :destroy, :move_to_trash]
  before_action :set_folder, only: [:show, :edit, :update, :destroy, :move_to_trash, :upload_file]
  helper_method :get_folder_path, :move_to_trash

  # GET /folders
  # GET /folders.json
  def index
    @folder = find_mytopbox
    redirect_to_mytopbox   #redirect_to_mytopbox
  end

  # GET /folders/1
  # GET /folders/1.json
  def show
    @my_folders = get_my_folders
    @my_documents = get_my_documents
    @folder_content = get_my_folders + get_my_documents
    @initial_index = 1
    @page = [params[:pg].to_i,1].max
    @initial_index = (@page-1)*PAGE_MAX unless @page <= 1
    @folder_page_content = @folder_content[@initial_index-1..((@initial_index+6))]
    if has_folder? && !@folder.trash
      set_current_folder(@folder)
    else
      render 'permissions/denied'
    end
  end

  # GET /folders/new
  def new
    @folder = Folder.new
  end

  def shared
    permissions = Permission.where(user_id: get_current_user.id)
    @shared_files = permissions.select do |permission|
      (permission.privacy.shareable.trash ==  false)
    end
  end

  def upload
    @document = Document.new
    render 'upload'
  end

  # POST /folders
  # POST /folders.json
  def create
    @folder = Folder.new(get_folder_params, )
    @folder.parent = get_current_folder
    @folder.user = get_current_user
    if @folder.save
      set_current_folder(@folder)
      redirect_to_current_folder
    end
  end

  # GET /folders/1/edit
  def edit
    set_current_folder(@folder)
    if @folder.trash
      render "permissions/denied"
      
    end
  end

  # PATCH/PUT /folders/1
  # PATCH/PUT /folders/1.json
  def update
    parent_id = params.require(:folder).require(:parent)
    @parent = Folder.find(parent_id)
    respond_to do |format|
      @folder.parent = @parent
      if @folder.update(get_folder_params)
        format.html { redirect_to @folder, notice: folder_updated_msg(@folder.name) }
        format.json { render :show, status: :ok, location: @folder }
      else
        format.html { render :edit }
        format.json { render json: @folder.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /folders/1
  # DELETE /folders/1.json
  def destroy
    parent = @folder.parent
    folder_name = @folder.name
    @folder.destroy
    respond_to do |format|
      format.html { redirect_to parent, action: :show, notice: folder_destroyed_msg(folder_name) }
      format.json { head :no_content }
    end
  end


  # Returns the path of a folder
  public
  def get_folder_path(folder)
    full_path = folder.name
    divider = '<b style="color: #2251A6">  >  </b>'
    parent_folder = folder.parent
    until (parent_folder.nil?)
      full_path = (parent_folder.name + divider + full_path)
      parent_folder = parent_folder.parent
    end
    return full_path.html_safe
  end

    def show_trash
    @trash_documents = get_trash_documents
    @trash_folders = get_trash_folders
    render 'folders/trash'
  end
  def move_to_trash
    set_folder
    unless @folder == find_mytopbox 
      @folder.make_trash
      redirect_to_mytopbox
    end
  end

  def recycle
    set_folder
    unless @folder == find_mytopbox
      @folder.make_recycle
      redirect_to_mytopbox      
    end
  end

  def recycle_all
    get_trash_folders.each{|folder| folder.make_recycle}
    get_trash_documents.each{|document| document.make_recycle}
    redirect_to trash_path
  end


  def trash_destroy_all
    get_trash_folders.each{|folder| folder.destroy}
    get_trash_documents.each{|document| document.destroy}
    redirect_to trash_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_folder
    @folder = Folder.find(params[:id])
  end

  def get_folder_params
    params.require(:folder).permit(:name)
  end

  def has_folder?
    return @folder.user.id == get_current_user.id
  end

  def get_my_folders
    Folder.where(parent_id: @folder.id, user_id: get_current_user.id, trash: false)
  end

  def get_my_documents
    Document.where(folder_id: @folder.id, trash: false)
  end

  def get_trash_folders
    all_user_trash_folders = Folder.where(user: get_current_user, trash:true)
    no_parents= all_user_trash_folders.select{|folder| !folder.parent.trash}
  end

  def get_trash_documents
    all_trash_documents = Document.where(trash: true)
    all_user_trash_document = all_trash_documents.select {|document| document.folder.user == get_current_user && !(document.folder.trash)}
  end

end

app/helpers/folders_helper.rb
module FoldersHelper

  PAGE_MAX = 9
  NEW_FOLDER_NAME = "Nova Pasta"


  def folder_created_msg(folder_name)
    "A pasta #{folder_name} foi criada com sucesso."
  end

  def folder_destroyed_msg(folder_name)
    "A pasta #{folder_name} foi apagada."
  end

  def folder_updated_msg(folder_name)
    "A pasta #{folder_name} foi atualizada."
  end
end

app/views/folders/_create.html.erb
<div class="modal-header-primary">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title"> <%=t(:new_folder)%> </h4>
</div>
<div class="modal-body format">
    <%= form_for(Folder.new, :url => url_for(:action => 'create')) do |f| %>
    	<a class="subtitle"> <%=t(:new_folder)%> </a>
        <%= f.text_field :name, :value => t(:untitled_folder), :autofocus => true, :required => true, :class => 'form-control' %>
</div>
<div class="modal-footer">
	<!--Submit sign up form button-->
	<button type="button" class="btn btn-primary" data-dismiss="modal"> <%=t(:cancel)%> </button>
        <%= f.submit t(:create), class: 'btn btn-primary' %>
    <% end %>
    
</div>

app/views/folders/_mytopbox.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-sm-2">
  <%= render 'index'%>
  </div>
	<div class="col-sm-10">

	</div>
</div>
</div>

app/views/folders/_sidebar.html.erb
<div class="content-fluid">
	<ul class="nav nav-pills nav-stacked" >
	<li role="presentation"  >
	<%= link_to find_mytopbox, :onclick => 'refresh()' do%>
		<span class = "glyphicon glyphicon glyphicon-th-large blue"></span> <%= t(:mytopbox) %>
	<% end %></li>
	<li role="presentation" >
	<%= link_to :controller => :folders, :action => :shared  do%>
	<span class= "glypicon glyphicon glyphicon-share blue"> </span> <%= t(:shared) %>
	<% end %>	
	</li>
	<li role="presentation" >
		<%= link_to permissions_path do %>
			<span class= "glypicon glyphicon glyphicon-lock blue"> </span> 
			<%= t(:permissions) %>
			<% end %>
		</li>
	<li role="presentation" >
		<%= link_to trash_path do %>
		<span class = "glyphicon glyphicon glyphicon-trash blue"></span>
		<%= t(:trash) %>
		<% end %>
	</li>
	</ul>
</div>

app/views/folders/_upload.html.erb
<div class="modal-header-primary">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title"> <%= t(:send_doc)%> </h4>
</div>
<div class="modal-body format">
    <%= form_for(Document.new) do |f| %>
            <div class="field">
            <%= f.file_field :file, :autofocus => true, accept: 'text/plain' %>
            </div>
</div>
<div class="modal-footer">
    <!--Submit sign up form button-->
    <button type="button" class="btn btn-primary" data-dismiss="modal"> <%= t(:cancel)%> </button>
        <%= f.submit t(:send), class: 'btn btn-primary' %>
    <% end %> 
</div>

app/views/folders/edit.html.erb
<body class="login-bg">
    <div class="login-page">
      <div class="form">
        <%= form_for(@folder) do |f| %>
            
            <a class="subtitle">Nome da pasta</a>
            <%= f.text_field :name, :placeholder => @folder.name, :autofocus => true, :required => true, :class => "form-control" %>
            
            <p><a class="subtitle">Mover para:</a></p>

            <p><%= f.collection_select :parent, get_not_children_folders(@folder.children), :id, :name, {:selected => @folder.parent.id}, {class: "select"}%></p>
            <br>
            <br>
            <%= f.submit 'Salvar', class: 'btn btn-login' %>
        <% end %>
        <center>
        <%= link_to 'Ver ' + @folder.name, @folder %> |
        <%= link_to 'Voltar', folders_path, :onclick => 'refresh()' %>  
        </center>
      </div>
    </div>
</body>

app/views/folders/shared.html.erb
<div class="container-fluid">
<div class="row">
  <div class="col-sm-2">
  <%= render 'sidebar' %>
  </div>
<div class="col-sm-10">

  <p id="notice"><%= notice %></p>

  <table class="table table">

    <% unless Permission.where(user_id: get_current_user.id).length == 0 %>
        <thead>
        <tr class="subtitle">
          <th> <%= t(:name) %> </th>
          <th> <%= t(:owner) %> </th>
          <th> <%= t(:last_modification) %> </th>
          <th> <%= t(:options) %> </th>
        </tr>
        </thead>

      <!-- Documents -->
      <% @shared_files.each do |permission| %>
      <% document = permission.privacy.shareable %>
      <tr>
            <td>
            <%= content_tag('i', nil, class: 'glyphicon glyphicon glyphicon-file blue') %>           
            <%= link_to document.name + "." + document.extension, document %>
            </td>
            <td>
            <%= permission.privacy.shareable.user.get_name %>
            </td>
            <td><%= document.updated_at.localtime.strftime('%d/%m/%Y às %H:%M') %></td>
            <td>
            
            <%= link_to document_download_url(document) , data: { no_turbolink: true }, :target => "_blank", tooltip: t(:download_btn) do %>
                <%= content_tag('i', nil, class: 'glyphicon glyphicon-download-alt blue') %>
                <% end %>&nbsp&nbsp

            <% if document.privacy.permissions.any?{|permission| permission.user_id == get_current_user.id && permission.Editar?}%><%= link_to edit_document_path(document), tooltip: t(:edit_btn) do %>
                <%= content_tag('i', nil, class: 'glyphicon glyphicon-pencil blue') %>
                <% end %>&nbsp&nbsp
            <% end %>

            </td>
          </tr>
      <% end %> 
      </tbody>
    <% else %>
      <h2 class="light-silver"><center> <%= t(:nothing_shared)%> </center></h2>
    <% end %>
  </table>
</div>
    
</div>
</div>

app/views/folders/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render 'sidebar' %>
    </div>
    <div class="col-sm-10">
      <% set_current_folder(@folder) %>

      <p id="notice">
        <% unless notice.nil? %>
          <div class="alert alert-info" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <%= notice %>
          </div>
      <% end %>
      </p>

      <!-- Caminho clicável de pastas -->
      <ol class="breadcrumb">
        <% parents = [] %>
        <% parent = @folder.parent %>
        <%= until parent.nil? do %>
            <% parents.push(parent) %>
            <% parent = parent.parent %>
        <% end %>

        <% parents.reverse.each do |folder| %>
            <% if folder.name == ApplicationHelper::MAIN_FOLDER_NAME %>
                <li><%= link_to t(:mytopbox), folder, :onclick => 'refresh()' %></li>
            <% else %>
              <li><%= link_to folder.name, folder, :onclick => 'refresh()' %></li>
            <% end %>
        <% end %>

        <% if @folder.name == ApplicationHelper::MAIN_FOLDER_NAME %>
            <li class="active"> <%= t(:mytopbox) %> </li>
        <% else %>
            <li class="active"> <%= @folder.name unless @folder.nil? %></li>
        <% end %>
      </ol>

      <table class="table table-hover">

        <% unless @folder_page_content.empty? %>

            <thead>
            <tr class="subtitle">
              <th> <%= t(:name) %> </th>
              <th> <%= t(:last_modification) %> </th>
              <th> <%= t(:options) %> </th>
            </tr>
            </thead>

            <!-- Folders -->
            <% @folder_page_content.each do |item| %>
                <% if item.class== Folder %>
                    <% folder = item %>
                    <tr>
                      <td>
                        <%= content_tag('i', nil, class: 'glyphicon glyphicon glyphicon-folder-close white blue') %>
                        &nbsp&nbsp<%= link_to folder.name, folder, :onclick => 'refresh()' %>
                      </td>
                      <td><p class="text-muted">--</p></td>

                      <td><%= link_to edit_folder_path(folder), tooltip: t(:edit_btn) do %>
                            <%= content_tag('i', nil, class: 'glyphicon glyphicon-pencil blue') %>
                        <% end %>&nbsp&nbsp
                        <%= link_to folder_move_to_trash_path(folder), method: :post, data: {confirm: t(:confirm)}, tooltip: t(:trash_btn) do %>
                            <%= content_tag('i', nil, class: 'glyphicon glyphicon-trash blue') %>
                        <% end %>

                      </td>

                    </tr>
                <% else %>
                    <% document= item %>
                    <!-- Documents -->
                    <tr>
                      <td>
                        <% if document.extension.in?(DocumentsHelper::COMPRESSION_EXTENSIONS) %>
                            <%= image_tag('compressed_file_icon.png', :size => '15x15', :alt => 'logo') %>
                            &nbsp <%= document.name + "." + document.extension %>
                        <% else %>
                            <%= content_tag('i', nil, class: 'glyphicon glyphicon glyphicon-file blue') %>
                            &nbsp <%= link_to document.name + "." + document.extension, document %>
                        <% end %>

                      </td>
                      <td><p class="text-muted"><%= document.updated_at.localtime.strftime('%d/%m/%Y às %H:%M') %></p>
                      </td>

                      <td>

                        <% if document.extension.in?(DocumentsHelper::COMPRESSION_EXTENSIONS) %>

                            <%= link_to document_download_url(document), data: {no_turbolink: true}, :target => "_blank", tooltip: t(:download_btn) do %>                            
                               <%= content_tag('i', nil, class: 'glyphicon glyphicon-download-alt blue') %>
                            <% end %>&nbsp&nbsp

                            <%= link_to document_decompress_url(document), method: :post, :onclick => 'refresh()', tooltip: t(:zip_btn) do %>
                                <%= content_tag('i', nil, class: 'glyphicon glyphicon-compressed blue') %>
                            <% end %>&nbsp&nbsp

                            <%= link_to document_move_to_trash_path(document), method: :post, data: {confirm: t(:confirm)}, tooltip: t(:trash_btn) do %>
                                <%= content_tag('i', nil, class: 'glyphicon glyphicon-trash blue') %>
                            <% end %>&nbsp&nbsp

                        <% else %>

                            <%= link_to edit_document_path(document), tooltip: t(:edit_btn) do %>
                                <%= content_tag('i', nil, class: 'glyphicon glyphicon-pencil blue') %>
                            <% end %>&nbsp&nbsp

                            <%= link_to new_permission_path + '?p='+document.privacy.id.to_s, data: {no_turbolink: true}, tooltip: t(:share_btn) do %>
                                <%= content_tag('i', nil, class: 'glyphicon glyphicon-share blue') %>
                            <% end %>&nbsp&nbsp

                            <%= link_to document_download_url(document), data: {no_turbolink: true}, :target => "_blank", tooltip: t(:download_btn) do %>
                                <%= content_tag('i', nil, class: 'glyphicon glyphicon-download-alt blue') %>
                            <% end %>&nbsp&nbsp

                            <content class="dropdown">
                              <button style="background-color: transparent; border: none; outline: none;" data-toggle="dropdown", tooltip="Comprimir">
                                <span class="glyphicon glyphicon-compressed blue"></span></button>
                              <ul class="dropdown-menu btn-sm">
                                <li><%= link_to t(:compress_gzip), document_compress_url(document, :compression_method => 'gz'), method: :post, :onclick => 'refresh()' %></li>
                                <li><%= link_to t(:compress_zip), document_compress_url(document, :compression_method => 'zip'), method: :post, :onclick => 'refresh()' %></li>
                              </ul>
                            </content>

                            <%= link_to document_move_to_trash_path(document), method: :post, data: {confirm: t(:confirm)}, tooltip: t(:trash_btn) do %>
                                <%= content_tag('i', nil, class: 'glyphicon glyphicon-trash blue') %>
                            <% end %>&nbsp&nbsp

                        <% end %>
                <% end %>
                </td>

                </tr>

            <% end %>
            </tbody>

        <% else %>
            <h2 class="light-silver">
              <center>
                <% if @folder == find_mytopbox && @page== 1 %>
                    <%= t(:empty_topbox) %> <br/>
                    <%= image_tag('open_box.png', :size => '150x150', :alt => t(:new_folder), :onclick => 'refresh()') %>
                    <br/>
                    <small class="light-silver">
                      <% t(:create_first_file) %> </small>
                <% else %>
                    <%= t(:empty_fold) %>  <br/>
                    <%= image_tag('open_box.png', :size => '100x100', :alt => t(:new_folder), :onclick => 'refresh()') %>
                    <br/>
                <% end %>
              </center>
            </h2>
        <% end %>
      </table>
      <nav aria-label="...">
        <ul class="pager">
          <% unless @page<=1 %>
              <li><a onclick='refresh()' href=<%= '?pg=' + (@page-1).to_s %>> <%= t(:previous) %> </a></li>
          <% end %>
          <% if ((@folder_content.length / FoldersHelper::PAGE_MAX)> (@page-1)) %>
              <li><a onclick='refresh()' href=<%= '?pg=' + (@page+1).to_s %>> <%= t(:next) %> </a></li>
          <% end %>
        </ul>
      </nav>


      <!-- Folder Modal -->
      <div id="createFolderModal" class="modal" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <%= render 'folders/create' %>
          </div>
        </div>
      </div>

      <!-- Document Modal -->
      <div id="createDocumentModal" class="modal" role="dialog" autofocus="true">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <%= render 'documents/create' %>
          </div>

        </div>
      </div>

      <!-- Upload Modal -->
      <div id="uploadDocumentModal" class="modal" role="dialog" autofocus="true">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <%= render 'folders/upload' %>
          </div>

        </div>
      </div>

      <!-- Menu -->
      <div id="menu" class="modal fade" role="dialog">
        <div class="btn-menu">

          <button type="button" class='btn btn-info btn-primary btn-circle btn-xl opm' data-modal="#uploadDocumentModal">
            <content class='glyphicon glyphicon-cloud-upload'/>
          </button>

          <button type="button" class='btn btn-info btn-primary btn-circle btn-xl opm' data-modal="#createDocumentModal">
            <content class='glyphicon glyphicon-file'/>
          </button>


          <button type="button" class='btn btn-info btn-primary btn-circle btn-xl opm' data-modal="#createFolderModal">
            <content class='glyphicon glyphicon-folder-open'/>
          </button>


          <% unless @folder == find_mytopbox %>

              <%= link_to @folder, method: :delete, data: {confirm: t(:confirm)}, class: 'btn btn-info btn-primary btn-circle btn-xl' do %>
                  <%= content_tag('i', nil, class: 'glyphicon glyphicon-trash white') %>
              <% end %>

              <%= link_to edit_folder_path(@folder.id), class: 'btn btn-primary btn-circle btn-xl' do %>
                  <%= content_tag('i', nil, class: 'glyphicon glyphicon-pencil white') %>
              <% end %>

          <% end %>

        </div>
      </div>


    </div>
  </div>

  <div class="footer">
    <button type="button" data-toggle="modal" data-target="#menu" class="btn btn-primary btn-circle btn-xl lower-right">
      <i class="glyphicon glyphicon-plus"></i></button>
  </div>


</div>

app/views/folders/trash.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render 'sidebar' %>
    </div>
    <div class="col-sm-10">

      <p id="notice">
        <% unless notice.nil? %>
          <div class="alert alert-info" role="alert">
            <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
            <%= notice %>
          </div>
        <% end %>
      </p>

     

      <table class="table table-hover">
        <% unless @trash_folders.empty? && @trash_documents.empty? %>

        <!-- Basic Menu -->
        <div class="content-fluid">
          <div class="col-sm-offset-3 col-sm-7" >
          <ul class="nav nav-pills" >
          <li role="presentation"  >
          <%= link_to recycle_all_path, method: :post, data: {confirm: t(:confirm)}, :onclick => 'refresh()' do%>
            <span class = "glyphicon glyphicon glyphicon-repeat white"></span> <%= t(:restore)%>
          <% end %></li>
          <li role="presentation"  >
          <%= link_to trash_destroy_all_path, method: :post, data: {confirm: t(:confirm_empty)}, :onclick => 'refresh()' do%>
            <span class = "glyphicon glyphicon glyphicon-trash white"></span> <%= t(:empty)%> 
          <% end %></li>
          </ul>
          </div>
          </div>


            <thead>
            <tr class="subtitle">
              <th> <%= t(:name) %> </th>
              <th> <%= t(:last_modification) %> </th>
              <th> <%= t(:options) %> </th>
            </tr>
            </thead>

          <!-- Folders -->
          <% @trash_folders.each do |folder| %>
              <tr >
                <td>
                <%= content_tag('i', nil, class: 'glyphicon glyphicon glyphicon-folder-close white blue') %>
                &nbsp&nbsp<%= link_to folder.name, folder, :onclick => 'refresh()' %>
                </td>
                <td><p class="text-muted">--</p></td>

                <td><%= link_to folder_recycle_path(folder), method: :post, tooltip: t(:recover_btn) do %>
                <%= content_tag('i', nil, class: 'glyphicon glyphicon-repeat blue') %>
                <% end %>&nbsp&nbsp
                <%= link_to folder, method: :delete, data: {confirm: 'Você tem certeza?'}, tooltip: t(:delete_btn)  do %>
                    <%= content_tag('i', nil, class: 'glyphicon glyphicon-trash blue') %>
                <% end %>

                </td>              

              </tr>
          <% end %>

          <!-- Documents -->
          <% @trash_documents.each do |document| %>
              <tr >
                <td>
                <%= content_tag('i', nil, class: 'glyphicon glyphicon glyphicon-file blue') %>           
                &nbsp <%= link_to document.name + "." + document.extension, document %>
                </td>
                <td><p class="text-muted"><%= document.updated_at.localtime.strftime('%d/%m/%Y às %H:%M') %></p></td>

                <td>
                <%= link_to document_recycle_path(document), method: :post, tooltip: t(:recover_btn) do %>
                <%= content_tag('i', nil, class: 'glyphicon glyphicon-repeat blue') %>
                <% end %>&nbsp&nbsp

                <%= link_to document_url(document), method: :delete, data: {confirm: t(:confirm)}, tooltip: t(:delete_btn) do %>
                    <%= content_tag('i', nil, class: 'glyphicon glyphicon-trash blue') %>
                <% end %>&nbsp&nbsp

                </td> 

              </tr>

          <% end %>
          </tbody>

        <% else %>
          <h2 class="light-silver">
          <center>
              <%= t(:empty_msg)%>
              <%= image_tag('open_box.png', :size =>'100x100' ,:alt => t(:new_folder), :onclick => 'refresh()') %><br />
                  </center></h2>
        <% end %>
      </table>

     

    </div>
  </div>
 
</div>