config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :privacies
  resources :permissions
  resources :users
  resources :documents
  resources :folders, :path => 'mytopbox'
  resources :permissions

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  #Login / Sign Up / Session
  root 'sessions#new'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #recycle
  post "documents/:id/recycle" => "documents#recycle", as: :document_recycle
  post "documents/:id/trash" => "documents#move_to_trash", as: :document_move_to_trash
  post "folders/:id/recycle" => "folders#recycle", as: :folder_recycle
  post "folders/:id/trash" => "folders#move_to_trash", as: :folder_move_to_trash
  get "trash" => "folders#show_trash"
  post "trash/recycle" => "folders#recycle_all", as: :recycle_all
  post "trash/destroy_all" => "folders#trash_destroy_all", as: :trash_destroy_all


  get 'denied' => 'permissions#denied'
  get 'makeopen' => 'privacies#open'
  get 'shared' => 'folders#shared'
  get 'notifications' => 'notification#index'
  get 'documents/:id/visibility' => 'privacies#switch_visibility', :as => 'document_visibility'
  get 'documents/:id/download' => 'documents#download', :as => 'document_download'
  post 'documents/:id/compress' => 'documents#compress', :as => 'document_compress'
  post 'documents/:id/decompress' => 'documents#decompress', :as => 'document_decompress'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  match "/auth/:provider/callback" => "sessions#create", as: :auth_callback, via: [:get, :post]


end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notified_by, class_name: 'User'
  belongs_to :user
  belongs_to :notifiable, polymorphic: true, :dependent => :destroy
  validates :user_id, :notified_by_id, :notifiable_id, presence: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  def index
    @notifications = Notification.all
  end

  def show
    @notification.update read: true
    redirect_to @notification.notifiable
  end

  def new
    @notification = Notification.new
  end

  def edit
  end


  def create(document_name)
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.fetch(:notification, {})
    end


end

app/helpers/notifications_helper.rb
module NotificationsHelper


end

app/views/notifications/_form.html.erb
<%= form_for(notification) do |f| %>
  <% if notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/_index.html.erb
<div class="pre-scrollable">
  <div class="container">
    <strong> <%= t(:notifications)%> </strong>
    <% if current_user_notifications.empty? %>
      <li><%= t(:not_dft_msg) %></li>
    <% end %>
    <ul class="list-group">
    <%  current_user_notifications.each do |notification| %>
      <% notification.read ? state = 'disabled' : state ='' %>
      <% mode1 = '<a href='+ notification_url(notification) + ' class="list-group-item list-group-item-action '+ state+'" style="border: none" >' %>
      <%= mode1.html_safe %>
      <p>
        <strong><%= notification.notified_by.get_name %></strong> <%= t(:notf_1)%>
        <strong><%= notification.notifiable.name%></strong> <%= t(:notf_2)%>
        <h6> <span class ="glyphicon glyphicon-time"> </span> <%= t(:notf_3)%> <%= ((Time.parse(DateTime.now.to_s) - Time.parse(notification.created_at.to_s))/3600).round(0) %> <%= t(:notf_4)%> </h6></p>
      </a>
    <% end %>
    </ul>
  </div>
</div>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/link_through.html.erb
<h1>Notifications#link_through</h1>
<p>Find me in app/views/notifications/link_through.html.erb</p>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>