config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :privacies
  resources :permissions
  resources :users
  resources :documents
  resources :folders, :path => 'mytopbox'
  resources :permissions

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  #Login / Sign Up / Session
  root 'sessions#new'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #recycle
  post "documents/:id/recycle" => "documents#recycle", as: :document_recycle
  post "documents/:id/trash" => "documents#move_to_trash", as: :document_move_to_trash
  post "folders/:id/recycle" => "folders#recycle", as: :folder_recycle
  post "folders/:id/trash" => "folders#move_to_trash", as: :folder_move_to_trash
  get "trash" => "folders#show_trash"
  post "trash/recycle" => "folders#recycle_all", as: :recycle_all
  post "trash/destroy_all" => "folders#trash_destroy_all", as: :trash_destroy_all


  get 'denied' => 'permissions#denied'
  get 'makeopen' => 'privacies#open'
  get 'shared' => 'folders#shared'
  get 'notifications' => 'notification#index'
  get 'documents/:id/visibility' => 'privacies#switch_visibility', :as => 'document_visibility'
  get 'documents/:id/download' => 'documents#download', :as => 'document_download'
  post 'documents/:id/compress' => 'documents#compress', :as => 'document_compress'
  post 'documents/:id/decompress' => 'documents#decompress', :as => 'document_decompress'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  match "/auth/:provider/callback" => "sessions#create", as: :auth_callback, via: [:get, :post]


end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :folder
  has_one :privacy, as: :shareable, :dependent => :destroy
  has_many :notifications, as: :notifiable, :dependent => :destroy
  enum extension: [:txt, :md, :gz, :zip]

  def user
  	return self.folder.user
  end

  def get_nome
    self.name
  end

  def make_trash
    self.update trash: true
  end

  def make_recycle
    self.update trash: false
  end

  def primary_extensions
    Document.extensions.keys.to_a - ["gz", "zip"]
  end

  def initialize(params = {})
    file = params.delete(:file)
    super
      if file
        file_name = sanitize_filename(file.original_filename)
        dot = file_name.index(".")
        len = file_name.length
        ext = file_name[dot+1..len]
        if (ext == 'txt' || ext == 'md') 
          self.name = file_name[0...dot]
          self.extension = file_name[dot+1..len]
          self.content = file.read
        end
      end
  end

  private
    def sanitize_filename(filename)
      # Get only the filename, not the whole path (for IE)
      # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
      return File.basename(filename)
  end

end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include DocumentsHelper, ApplicationHelper
  helper_method :share, :user, :download, :recycle

  def user
    return @document.folder.user
  end

  def new
    @document = Document.new
  end

  def create
    @file = params.delete(:file)
    @document = Document.new(get_document_params)
    @document.folder = get_current_folder
    privacy = Privacy.new
    privacy.shareable = @document
    @document.privacy = privacy
    if @file 
      @document.content = file.read
    end
    if @document.save
      redirect_to_current_folder
    end
  end

  def index
    @documents = Document.all
  end

  def show
    @document = Document.find(params[:id])
      unless has_read_permission? 
        render "permissions/denied"
      end
      if @document.trash
        render "permissions/denied"
      end
  end

  def move_to_trash
    @document = Document.find(params[:id])
    @document.make_trash 
    redirect_to_current_folder
  end

  def recycle
    @document = Document.find(params[:id])
    @document.update trash: false
    @document.make_recycle
    redirect_to @document
  end

  def download
    @document = Document.find(params[:id])
    filename = @document.name + "." + @document.extension
    send_data @document.content, :filename => filename
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to MAIN_FOLDER_PATH + get_current_folder.id.to_s
  end

  def edit
    @document = Document.find(params[:id])
    unless (has_edit_permission? and !@document.trash)
      redirect_to MAIN_FOLDER_PATH
    end
  end

  def share
    @document = Document.find(params[:id])
    redirect_to share_permission_path + '?d='+@document.id.to_s
  end

  def update
    @document = Document.find params[:id]
    unless (@document.user != get_current_user)
      folder_id = params.require(:document).require(:folder)
      @folder = Folder.find(folder_id)
      @document.folder = @folder
    end
    @document.update_attributes(get_document_params)
    
    redirect_to action: ACTION_SHOW, id: @document
  end

  def compress
    @document = Document.find(params[:id])
    compression_method = get_compression_method(params[:compression_method])
    @document.content = compression_method.compress(@document.content)
    @document.name += ('.' + @document.extension)
    @document.extension = compression_method.get_extension
    @document.save
    redirect_to :controller => 'folders', :action => 'index'
  end

  def decompress
    @document = Document.find(params[:id])
    compression_method = get_compression_method(@document.extension)
    @document.content = compression_method.decompress(@document.content)
    @document.extension = get_extension_out_of_name(@document.name)
    @document.name = @document.name[0..(-@document.extension.length - 2)]
    @document.save
    redirect_to :controller => 'folders', :action => 'index'
  end
  
  private
  def get_document_params
    params.require(:document).permit(:name, :content, :extension, :file)
  end

    def has_edit_permission?
    return true if is_in_user_folders?(@document.folder)
    @document.privacy.permissions.each do |permission|
      return true if ((permission.user_id == get_current_user.id) and permission.Editar?)
    end
    return false
  end

  def has_read_permission?
    return true if @document.privacy.open?
    return false if get_current_user.nil?
    return true if has_edit_permission?
    @document.privacy.permissions.each do |permission|
      return true if (permission.user_id == get_current_user.id)
    end
    return false
  end

  def is_in_user_folders?(folder)
    return false if folder.nil?
    if folder.user == get_current_user
      return true
    else
      return is_in_user_folders?(folder.parent)
    end
  end

  def get_compression_method(extension)
    if extension == GzipMethod.get_extension
      return GzipMethod
    elsif extension == ZipMethod.get_extension
      return ZipMethod
    end
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper

    COMPRESSION_EXTENSIONS = ['gz', 'zip']

    def get_extension_out_of_name(title)
        extension = ''
        title.reverse.each_char do |char|
           unless char == '.'
               extension = char + extension
           else
            return extension
           end
        end
    end

end

app/views/documents/_create.html.erb
<div class="modal-header-primary">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title"> <%=t(:new_doc)%> </h4>
</div>
<div class="modal-body format">
    <%= form_for(:document, :url => url_for(:controller => 'documents', :action => 'create')) do |f| %>
    	<a class="subtitle"> <%=t(:new_doc)%> </a>
        <%= f.text_field :name, :value => t(:untitled_doc), :autofocus => true, :required => true, :class => 'form-control' %>
        <br>
        <p><a class="subtitle"> <%=t(:extension)%> </a></p>

        <p><%= f.collection_select :extension, Document.extensions.keys.to_a - ["gz", "zip"], :to_s, :to_s, {:selected => Document.extensions.keys.to_a[0]}, {class: "select"}%></p>
        <br>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-primary" data-dismiss="modal"> <%=t(:cancel)%> </button>
		<%= f.submit t(:create), class: 'btn btn-primary' %>
    <% end %>
    
</div>

app/views/documents/edit.html.erb
<body>
	<script type="text/javascript">
		if(location.search.indexOf('reloaded=yes') < 0){
		var hash = window.location.hash;
		var loc = window.location.href.replace(hash, '');
		loc += (loc.indexOf('?') < 0? '?' : '&') + 'reloaded=yes';
		setTimeout(function(){window.location.href = loc + hash;}, 0);
		}
	</script>

	<br>
	<div class="content">
		<%= form_for @document do |d| %>
			<div class="col-lg-12">
				<a class="subtitle"> <%= t(:title) %>: </a>
	    			<div class="input-group">
		      			<%= d.text_field :name, class: 'form-control' %>
		      			<!-- Extension select dropdown -->
		      			<div class="input-group-btn">
		      				<%= d.collection_select :extension, @document.primary_extensions, :to_s, :to_s, {:selected => @document.extension}, {class: "btn btn-default dropdown-toggle" }%>
		      			</div>
	    			</div>				
		    		<br>
			    	<p>
				    	<% if @document.md? %>
				            <%= d.bootsy_area(:content, class: 'form-control doc-area', rows: 18) %>
				        <% else %>
				              <%= d.text_area(:content, class: 'form-control doc-area', rows: 18) %>
				        <% end %>
			        </p>
				    <% if @document.user == get_current_user %>
				    	<p><a class="subtitle"> <%= t(:move_to)%>: </a></p>
				    	<p><%= d.collection_select :folder, get_user_folders, :id, :name, {:selected => @document.folder.id}, {class: "select"}%></p>
			            <br>
		            <% end %>

				<!-- Basic Menu -->
		        <div class="content-fluid">
		          <div class="col-sm-offset-4 col-sm-8" >
				        <ul class="list-inline" >
							<li>
					          <%= link_to t(:cancel), get_current_folder, class: 'btn btn-primary', :onclick => 'refresh()' %>
					        </li>
					        <li>
					          <%= link_to t(:share), new_permission_path + '?p='+@document.privacy.id.to_s, data: { no_turbolink: true }, class: ' btn btn-primary '   %>
					       	</li>
					        <li role="presentation" class="active" >
					          <%= d.submit t(:save),:class => "btn btn-primary" do %>
					          <% end %>
					        </li>
				        </ul>
		          	</div>
		        </div>

		  	</div>
	  	<% end %>
	</div>
</body>

app/views/documents/index.html.erb
<table>
  <tr>
    <th>ID      </th>
    <th>Nome    </th>
    <th>Conteudo</th>
    <th>Folder </th>
  </tr>

  <% @documents.each do |document| %>
      <tr>
        <td><%= document.id    %></td>
        <td><%= document.name    %></td>
        <td><%= document.content %></td>
        <td><%= document.folder.name %></td>

        <td><%= link_to 'Show', document, action: :show %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

<!-- Redireciona para a action new do controller_document -->
<%= link_to 'Novo', action: 'new' %>

app/views/documents/show.html.erb
<body class="login-bg">
<div class= "container-fluid"> 
  <div class="row pull-center" >
    <div class="col-sm-offset-2 col-sm-8 pull-center" >
      <div class="document-show"><center>
        <h1><strong><%= @document.name %> </strong></h1></center><br />
        
  		  <p>
          <% if @document.md? %>
            <%= @document.content.try(:html_safe) %>
          <% else %>
            <%= sanitize @document.content.gsub(/\n/,"<br/>"), :tags => ['br']  %>
          <% end %>
        </p>

        
      <div class="list-group-item" >
       
          <div class= "container-fluid"> 

            <div class="col-sm-3">
              <b class="subtitle"> <%= t(:authors) %> </b>
              <p align=left>
                <%= @document.user.first_name %> <br />
                <% @document.privacy.permissions.each do |permission| %>
                  <% if permission.status == "Editar" %>
                   <%= User.find(permission.user_id).first_name %> <br />
                  <% end %>
               <% end %> </p>
             </div>  

          <div class="col-sm-4">
            <b class="subtitle"> <%= t(:publication_date)%> </b>
            <p align=left>
              <%= @document.updated_at.localtime.strftime('%d/%m/%Y às %H:%M') %> <br />
            </p>
          </div>  

          <div class="col-sm-5">
            <% unless get_current_user.nil? %>
              <% if @document.user.id == get_current_user.id || @document.privacy.permissions.any?{|permission| permission.user_id == get_current_user.id && permission.Editar?}%> 
                <%= link_to edit_document_path(@document), tooltip: t(:edit_btn) do %>
                  <%= content_tag('i', nil, class: 'glyphicon glyphicon-pencil blue')%>
                <% end %> &nbsp&nbsp
     
              <%= link_to document_download_url(@document), data: { no_turbolink: true }, :target => "_blank", tooltip: t(:download_btn) do  %> 
                <content class='glyphicon glyphicon-download-alt blue'/> 
              <% end %>  &nbsp&nbsp
              
              <% if @document.user.id == get_current_user.id %>
                <%= link_to new_permission_path + '?p='+@document.privacy.id.to_s, data: { no_turbolink: true }, tooltip: t(:share_btn) do %>
                  <%= content_tag('i', nil, class: 'glyphicon glyphicon-share blue') %>
                <% end %>
              <% end %>
            <% end %> &nbsp&nbsp

           <% if @document.user.id == get_current_user.id %>
            <%= link_to document_visibility_url(@document),  data: { no_turbolink: true }, tooltip: t(:share_link_btn) do %>
              <%= content_tag('i', nil, class: 'glyphicon glyphicon-link blue') %>
              <% end %>
              <% if @document.privacy.open? %>
                <span class="label label-success"> <%= t(:activated)%> </span>
                <span class="input-group-addon" id="basic-addon3"><%= document_url(@document) %></span>
              <% else %>
            <span class="label label-default"> <%= t(:disabled)%> </span>
            <% end %><br />
          <% end %>
          <% end %>

          </div>
        </div>
  </div><br />
  <div
            class="fb-like"
            data-share="true"
            data-show-faces="true">
          </div>

      </div>
    </div>
  </div>
  <div class="row" >

    <div class="col-sm-offset-2 col-sm-8" style="border: none" >
  
</div>
</div>
</div>
</body>