config/routes.rb
Rails.application.routes.draw do
  resources :notifications
  resources :privacies
  resources :permissions
  resources :users
  resources :documents
  resources :folders, :path => 'mytopbox'
  resources :permissions

  mount Bootsy::Engine => '/bootsy', as: 'bootsy'

  #Login / Sign Up / Session
  root 'sessions#new'
  get 'signup'  => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  #recycle
  post "documents/:id/recycle" => "documents#recycle", as: :document_recycle
  post "documents/:id/trash" => "documents#move_to_trash", as: :document_move_to_trash
  post "folders/:id/recycle" => "folders#recycle", as: :folder_recycle
  post "folders/:id/trash" => "folders#move_to_trash", as: :folder_move_to_trash
  get "trash" => "folders#show_trash"
  post "trash/recycle" => "folders#recycle_all", as: :recycle_all
  post "trash/destroy_all" => "folders#trash_destroy_all", as: :trash_destroy_all


  get 'denied' => 'permissions#denied'
  get 'makeopen' => 'privacies#open'
  get 'shared' => 'folders#shared'
  get 'notifications' => 'notification#index'
  get 'documents/:id/visibility' => 'privacies#switch_visibility', :as => 'document_visibility'
  get 'documents/:id/download' => 'documents#download', :as => 'document_download'
  post 'documents/:id/compress' => 'documents#compress', :as => 'document_compress'
  post 'documents/:id/decompress' => 'documents#decompress', :as => 'document_decompress'

  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale

  match "/auth/:provider/callback" => "sessions#create", as: :auth_callback, via: [:get, :post]


end

app/models/privacy.rb
class Privacy < ApplicationRecord
  belongs_to :shareable, polymorphic: true
  enum visibility: [ :closed, :open ]
  has_many :permissions, :dependent => :destroy, :foreign_key => 'privacy_id'

  def get_shareable
    return self.shareable
  end

end

app/controllers/privacies_controller.rb
class PrivaciesController < ApplicationController
  before_action :set_privacy, only: [:show, :edit, :update, :destroy]

  # GET /privacies
  # GET /privacies.json
  def index
    @privacies = Privacy.all
  end

  # GET /privacies/1
  # GET /privacies/1.json
  def show
  end

  # GET /privacies/new
  def new
    @privacy = Privacy.new
  end

  # GET /privacies/1/edit
  def edit
  end

  def switch_visibility
    document = Document.find(params[:id])
    @privacy = document.privacy
    if @privacy.visibility == "open"
      @privacy.update visibility: "closed"
    else
      @privacy.update visibility: "open"
    end
    redirect_to document
  end

  # POST /privacies
  # POST /privacies.json
  def create
    @privacy = Privacy.new(privacy_params)

    respond_to do |format|
      if @privacy.save
        format.html { redirect_to @privacy, notice: 'Privacy was successfully created.' }
        format.json { render :show, status: :created, location: @privacy }
      else
        format.html { render :new }
        format.json { render json: @privacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /privacies/1
  # PATCH/PUT /privacies/1.json
  def update
    respond_to do |format|
      if @privacy.update(privacy_params)
        format.html { redirect_to @privacy, notice: 'Privacy was successfully updated.' }
        format.json { render :show, status: :ok, location: @privacy }
      else
        format.html { render :edit }
        format.json { render json: @privacy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /privacies/1
  # DELETE /privacies/1.json
  def destroy
    @privacy.destroy
    respond_to do |format|
      format.html { redirect_to privacies_url, notice: 'Privacy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_privacy
      @privacy = Privacy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def privacy_params
      params.require(:privacy).permit(:document_id)
    end
end

app/helpers/privacies_helper.rb
module PrivaciesHelper
end

app/views/privacies/_form.html.erb
<%= form_for(privacy) do |f| %>
  <% if privacy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(privacy.errors.count, "error") %> prohibited this privacy from being saved:</h2>

      <ul>
      <% privacy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :document_id %>
    <%= f.text_field :document_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/privacies/edit.html.erb
<h1>Editing Privacy</h1>

<%= render 'form', privacy: @privacy %>

<%= link_to 'Show', @privacy %> |
<%= link_to 'Back', privacies_path %>

app/views/privacies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Privacies</h1>

<table>
  <thead>
    <tr>
      <th>Document</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @privacies.each do |privacy| %>
      <tr>
        <td><%= privacy.shareable.name %></td>
        <td><%= link_to 'Show', privacy %></td>
        <td><%= link_to 'Edit', edit_privacy_path(privacy) %></td>
        <td><%= link_to 'Destroy', privacy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Privacy', new_privacy_path %>

app/views/privacies/new.html.erb
<h1>New Privacy</h1>

<%= render 'form', privacy: @privacy %>

<%= link_to 'Back', privacies_path %>

app/views/privacies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document:</strong>
  <%= @privacy.shareable.name %>
  <br>
  <strong>permissions:</strong>
  <%= link_to @privacy.visibility %>
  <%=@privacy.permissions%>
</p>

<%= link_to 'Edit', edit_privacy_path(@privacy) %> |
<%= link_to 'Back', privacies_path %>